#!/usr/bin/env bash
# generated-file-ownership.sh — every WHOLE-FILE generated source is owner:fork.
#
# WHY THIS EXISTS
# customization-surface.yaml already states the rule — "WHOLE-FILE generated => owner:fork, the same
# call as GeneratedApiBindings" — but nothing enforced it, and it has now been broken twice.
#
# The failure is quiet. A whole-file generated source is derived from app-profile, which after the
# union-by-identity merge contains the FORK's rows as well as the template's. Declare it owner:template
# and a sync BLIND-COPIES the template's version over it: the fork's DAO bindings / cache keys / store
# qualifiers vanish, nothing conflicts, nothing errors, and the tree still compiles against whatever
# the template happened to declare. It stays wrong until someone re-runs syncForkConfig.
#
# Region-generated files are the opposite case and correctly owner:template: the file is full-copied
# and its `gen-*` regions are re-derived afterwards, so the template's structure SHOULD win.
#
# CONTRACT
#   GFO-1 a .kt carrying a generated-by banner and NO gen-region markers resolves owner:fork
#   GFO-2 the resolver actually matched a rule — an unmatched path means the catch-all decided it,
#         which is how this was missed in the first place
set -uo pipefail
: "${HEALTH_ROOT:?generated-file-ownership: HEALTH_ROOT not set (run via product-health.sh)}"
SURFACE_SH="${GFO_SURFACE_SH:-$HEALTH_ROOT/scripts/customization-surface.sh}"
SURFACE_YAML="${GFO_SURFACE_YAML:-$HEALTH_ROOT/customization-surface.yaml}"
fail=0
checked=0

[ -f "$SURFACE_YAML" ] || { echo "⚠️  generated-file-ownership skipped — no $SURFACE_YAML"; exit 0; }
[ -x "$SURFACE_SH" ]   || { echo "⚠️  generated-file-ownership skipped — no $SURFACE_SH"; exit 0; }

# Whole-file generated = carries the banner AND declares no gen-* / syncForkConfig:* regions.
while IFS= read -r f; do
  [ -n "$f" ] || continue
  grep -qE 'gen-[a-z-]+:begin|syncForkConfig:[a-z]+' "$f" && continue   # region-generated → template is right
  rel="${f#$HEALTH_ROOT/}"
  checked=$((checked + 1))
  owner="$(CS_CONTRACT="$SURFACE_YAML" bash "$SURFACE_SH" resolve-owner "$rel" 2>/dev/null)"
  if [ -z "$owner" ]; then
    echo "❌ GFO-2 $rel matches NO rule in customization-surface.yaml"
    echo "     → the catch-all decides its fate silently; declare it explicitly"
    fail=1
  elif [ "$owner" != "fork" ]; then
    echo "❌ GFO-1 $rel is whole-file generated but resolves owner:$owner — must be 'fork'"
    echo "     → a sync BLIND-COPIES the template's version over the fork's, dropping every row the"
    echo "       fork declared in app-profile, with no conflict and no error to notice"
    fail=1
  fi
done < <(grep -rlE 'GENERATED by .*syncForkConfig|GENERATED by store-ksp' \
           "$HEALTH_ROOT/core" "$HEALTH_ROOT/core-base" --include='*.kt' 2>/dev/null \
         | grep -v '/build/' | sort)

if [ "$fail" -eq 0 ]; then
  echo "✅ generated-file-ownership: $checked whole-file generated source(s), all owner:fork"
  exit 0
fi
echo "❌ generated-file-ownership: see above"
exit 1
