#!/usr/bin/env bash
# checks/migration-ledger.sh — the Room migration ledger is append-only and internally coherent.
#
# Room's schema version is ONE monotonic integer and migrations are edges between consecutive values,
# so the template and the fork cannot share the counter. The fork owns it outright
# (`app-profile/migration-ledger.yaml`); the template ships `migration_units` with a stable id and NO
# version (`core/database/migration-units.yaml`), and syncForkConfig appends each to the fork's next
# free slot.
#
# That only holds while the ledger's invariants hold, and the dangerous one is silent:
#
#   LG-1  the from/to chain is contiguous and `version` equals the last `to`
#   LG-2  APPEND-ONLY — no row already in git HEAD changed its from/to, and none was deleted
#   LG-3  a unit is applied at most once, and is never both baselined and migrated
#   LG-4  template units are ADDITIVE (adds_table / adds_column, never a spec) — a unit is replayed
#         at an arbitrary slot, so a rename or conditional drop breaks out of position
#   LG-5  ForkDatabaseConfig.VERSION agrees with the ledger
#   LG-6  AppDatabase's autoMigrations match the ledger row-for-row
#
# LG-2 is the one that matters most: a shipped from/to edge is a contract with every installed
# device. Renumbering it stands them on a version with no path forward, and nothing else here or in
# the compiler would notice — the tree still builds, the schema JSON still matches.
#
# exit 0 PASS / 1 FAIL. Ruby (like network-access-points.sh) — YAML + Kotlin in one pass.
set -uo pipefail
: "${HEALTH_ROOT:?migration-ledger: HEALTH_ROOT not set (run via product-health.sh)}"
LEDGER="${LG_LEDGER:-$HEALTH_ROOT/app-profile/migration-ledger.yaml}"
UNITS="${LG_UNITS:-$HEALTH_ROOT/core/database/migration-units.yaml}"
CFG="${LG_CFG:-$HEALTH_ROOT/core/database/src/commonMain/kotlin/kpt/core/database/config/ForkDatabaseConfig.kt}"
# AppDatabase is GENERATED by tools/database-ksp into build/, not committed source. Prefer the
# artifact; fall back to the old committed path so a fork mid-migration (and the canary fixtures,
# which are plain trees with no build/) still get audited rather than silently skipped.
DB_GEN="$HEALTH_ROOT/core/database/build/generated/ksp/metadata/commonMain/kotlin/kpt/core/database/AppDatabase.kt"
DB_SRC="$HEALTH_ROOT/core/database/src/commonMain/kotlin/kpt/core/database/AppDatabase.kt"
if [ -n "${LG_DB:-}" ]; then DB="$LG_DB"
elif [ -f "$DB_GEN" ]; then DB="$DB_GEN"
else DB="$DB_SRC"; fi

[ -f "$LEDGER" ] || { echo "no migration ledger — nothing to audit (ok)"; exit 0; }
command -v ruby >/dev/null 2>&1 || { echo "ruby unavailable — cannot audit the ledger"; exit 1; }

# LG-2 needs the committed version to diff against. Absent (new file / shallow clone) -> skip, loudly.
# An externally supplied LG_HEAD wins, so the canary can hand us a "previously committed" ledger.
# Without this the check recomputed HEAD_LEDGER from git and clobbered the override — which meant
# LG-2, the invariant that matters most, had no test at all while its RED leg went green on
# unrelated cascade failures.
HEAD_LEDGER="${LG_HEAD:-}"
if [ -z "$HEAD_LEDGER" ] && git -C "$HEALTH_ROOT" rev-parse --git-dir >/dev/null 2>&1; then
  HEAD_LEDGER="$(git -C "$HEALTH_ROOT" show "HEAD:app-profile/migration-ledger.yaml" 2>/dev/null || true)"
fi

LG_HEAD="$HEAD_LEDGER" ruby - "$LEDGER" "$UNITS" "$CFG" "$DB" <<'RUBY'
require 'yaml'
ledger_p, units_p, cfg_p, db_p = ARGV
fail = false
def bad(m)
  puts m
  true
end

led = YAML.safe_load(File.read(ledger_p)) rescue nil
unless led.is_a?(Hash)
  puts "❌ could not parse #{ledger_p}"; exit 1
end
rows = (led["migrations"] || []).select { |r| r.is_a?(Hash) && r["from"] && r["to"] }
version  = led["version"]
baseline = (led["baseline_units"] || []).map(&:to_s)

# ── LG-1 contiguous chain + version == last `to` ─────────────────────────────
rows.each_cons(2) do |a, b|
  next if a["to"] == b["from"]
  fail = bad("❌ LG-1 gap in the chain: #{a['from']}->#{a['to']} then #{b['from']}->#{b['to']}\n" \
             "     → Room needs an edge between consecutive versions; a device at #{a['to']} cannot reach #{b['to']}")
end
rows.each do |r|
  fail = bad("❌ LG-1 row #{r['from']}->#{r['to']} does not advance the version") if r["to"].to_i <= r["from"].to_i
end
if rows.any? && version != rows.last["to"]
  fail = bad("❌ LG-1 version is #{version} but the last migration ends at #{rows.last['to']}\n" \
             "     → the database would declare a version no migration reaches")
end
if rows.empty? && version.to_i != 1
  fail = bad("❌ LG-1 no migrations but version is #{version} — a fork with no history starts at 1")
end

# ── LG-3 a unit is applied once, and is never both baselined and migrated ────
applied = rows.map { |r| r["unit"].to_s }.reject(&:empty?)
# Ruby 2.6 on this runner — no Array#tally (2.7+).
dupes = applied.group_by { |x| x }.select { |_, v| v.size > 1 }.keys
fail = bad("❌ LG-3 unit(s) applied more than once: #{dupes.join(', ')}") if dupes.any?
both = applied & baseline
fail = bad("❌ LG-3 unit(s) both baselined AND migrated: #{both.join(', ')}\n" \
           "     → baseline means the fresh schema already contains it; migrating it again re-applies a no-op or fails") if both.any?

# ── LG-4 template units are additive ─────────────────────────────────────────
if File.exist?(units_p)
  units = YAML.safe_load(File.read(units_p)) rescue nil
  (units && units["migration_units"] || []).each do |u|
    next unless u.is_a?(Hash)
    id = u["id"].to_s
    unless u.key?("adds_table") || u.key?("adds_column")
      fail = bad("❌ LG-4 unit '#{id}' declares neither adds_table nor adds_column\n" \
                 "     → a unit is replayed at whatever slot each fork has free, so it must be additive")
    end
    if u.key?("spec")
      fail = bad("❌ LG-4 unit '#{id}' carries a spec — an AutoMigrationSpec implies a rename/drop, which\n" \
                 "     assumes a starting schema and breaks when replayed out of position")
    end
  end
end

# ── LG-5 the generated constant agrees with the ledger ───────────────────────
if File.exist?(cfg_p)
  v = File.read(cfg_p)[/const val VERSION\s*=\s*(\d+)/, 1]
  if v && v.to_i != version.to_i
    fail = bad("❌ LG-5 ForkDatabaseConfig.VERSION is #{v} but the ledger says #{version}\n" \
               "     → run `./gradlew syncForkConfig`")
  end
end

# ── LG-6 AppDatabase's autoMigrations match the ledger row-for-row ───────────
# The `gen-migrations` sentinel region is gone: AppDatabase is generated whole from the annotations,
# and its autoMigrations come from THIS ledger as a ksp arg. Drift is therefore impossible by
# construction — but only while that wiring holds, so the check stays and reads the emitted file.
# It must never silently skip: File.exist? returning false is exactly how this went vacuous when the
# file stopped being committed source, passing while checking nothing.
if File.exist?(db_p)
  src = File.read(db_p)
  block = src[/autoMigrations\s*=\s*\[(.*?)\]/m, 1].to_s
  emitted = block.scan(/AutoMigration\(from\s*=\s*(\d+),\s*to\s*=\s*(\d+)/).map { |f, t| [f.to_i, t.to_i] }
  expected = rows.map { |r| [r["from"].to_i, r["to"].to_i] }
  if emitted != expected
    fail = bad("❌ LG-6 AppDatabase's autoMigrations do not match the ledger\n" \
               "     emitted:  #{emitted.inspect}\n     ledger:   #{expected.inspect}\n" \
               "     → rebuild core/database (the list is generated from this ledger)")
  end
  lg6 = "#{emitted.size} autoMigration(s) match"
else
  # Not a failure: product-health is a pure-bash CI job with no Gradle, so on a fresh checkout the
  # artifact does not exist yet. Say so out loud rather than passing silently.
  lg6 = "autoMigrations unchecked (AppDatabase not built)"
end

# ── LG-2 APPEND-ONLY vs git HEAD ─────────────────────────────────────────────
head = ENV["LG_HEAD"].to_s
if head.strip.empty?
  puts "⚠️  LG-2 skipped — no committed ledger to diff against (new file or shallow clone)"
else
  old = YAML.safe_load(head) rescue nil
  old_rows = ((old.is_a?(Hash) && old["migrations"]) || []).select { |r| r.is_a?(Hash) && r["from"] }
  old_rows.each_with_index do |o, i|
    n = rows[i]
    if n.nil?
      fail = bad("❌ LG-2 row #{i + 1} (#{o['from']}->#{o['to']}, unit #{o['unit']}) was DELETED\n" \
                 "     → a shipped edge is a contract with installed devices; it can only be appended after")
    elsif n["from"] != o["from"] || n["to"] != o["to"]
      fail = bad("❌ LG-2 row #{i + 1} RENUMBERED: was #{o['from']}->#{o['to']}, now #{n['from']}->#{n['to']} (unit #{o['unit']})\n" \
                 "     → every device that already applied #{o['from']}->#{o['to']} is stranded; append instead")
    end
  end
end

if fail
  puts "     → ledger is app-profile/migration-ledger.yaml (fork-owned, APPEND-ONLY)."
  exit 1
end
puts "migration ledger: v#{version}, #{rows.size} row(s), #{baseline.size} baselined — chain contiguous, append-only, units additive; #{lg6}"
RUBY
