/*
 * Copyright 2025 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */
package kpt.core.database.config

import kpt.core.database.AppDatabase
import kpt.core.database.di.testPlatformModule
import org.koin.core.context.startKoin
import org.koin.core.context.stopKoin
import org.koin.mp.KoinPlatform
import kotlin.test.AfterTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class AppDatabaseTest {

    private var database: AppDatabase? = null

    @AfterTest
    fun teardown() {
        // stopKoin() must run even when a test failed before building, or the first fault leaks a
        // started Koin and every later test dies with KoinApplicationAlreadyStartedException —
        // one real failure reported as four.
        runCatching { database?.close() }
        stopKoin()
    }

    @Test
    fun inMemoryDatabaseCanBeCreated() {
        startKoin { modules(testPlatformModule) }
        database = KoinPlatform.getKoin().get()

        assertNotNull(database)
    }

    @Test
    fun databaseExposeAlertDao() {
        startKoin { modules(testPlatformModule) }
        database = KoinPlatform.getKoin().get()

        assertNotNull(database!!.alertDao)
    }

    @Test
    fun databaseExposeInterestRateSeriesDao() {
        startKoin { modules(testPlatformModule) }
        database = KoinPlatform.getKoin().get()

        assertNotNull(database!!.interestRateSeriesDao)
    }

    @Test
    fun databaseVersionIsCurrent() {
        // Bumped to 13 in the v12→v13 change that added `framework_submit_drafts.attemptCount`, so
        // OfflineSubmitSyncer can apply RetryPolicy backoff + the maxAttempts cap across restarts.
        // Matching AutoMigration(12→13) + 13.json export. Update this constant when bumping
        // AppDatabase.VERSION so the guardrail stays
        // meaningful. The full in-place upgrade chain is closed: AutoMigration hops exist for every
        // step up to 13 (incl. the 10→11 `cloud_todos` add that #274 originally omitted), so a v10
        // device upgrades cleanly to v13.
        assertEquals(13, AppDatabase.VERSION)
    }

    @Test
    fun databaseNameIsCorrect() {
        // Fork-unique, appId-derived (regenerated by syncForkConfig). DATABASE_NAME
        // delegates to the single source of truth, DatabaseConfig.NAME.
        assertEquals(DatabaseConfig.NAME, AppDatabase.DATABASE_NAME)
    }
}
