/*
 * Copyright 2025 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */
package kpt.core.database.config

import kpt.core.database.AppDatabase
import kpt.core.database.di.testPlatformModule
import org.koin.core.context.startKoin
import org.koin.core.context.stopKoin
import org.koin.mp.KoinPlatform
import kotlin.test.AfterTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class AppDatabaseTest {

    private var database: AppDatabase? = null

    @AfterTest
    fun teardown() {
        // stopKoin() must run even when a test failed before building, or the first fault leaks a
        // started Koin and every later test dies with KoinApplicationAlreadyStartedException —
        // one real failure reported as four.
        runCatching { database?.close() }
        stopKoin()
    }

    @Test
    fun inMemoryDatabaseCanBeCreated() {
        startKoin { modules(testPlatformModule) }
        database = KoinPlatform.getKoin().get()

        assertNotNull(database)
    }

    @Test
    fun databaseExposesClientDao() {
        startKoin { modules(testPlatformModule) }
        database = KoinPlatform.getKoin().get()

        assertNotNull(database!!.clientDao)
    }

    @Test
    fun databaseExposesLoanDao() {
        startKoin { modules(testPlatformModule) }
        database = KoinPlatform.getKoin().get()

        assertNotNull(database!!.loanDao)
    }

    @Test
    fun databaseVersionIsCurrent() {
        // 14: the 13→14 change dropped six inverted FOREIGN KEY constraints that made every insert
        // fail with SQLite 787, so the offline cache could never be written (see
        // `app-profile/migration-ledger.yaml`). Update this constant when bumping
        // `AppDatabase.VERSION` so the guardrail stays meaningful.
        assertEquals(14, AppDatabase.VERSION)
    }

    @Test
    fun databaseNameIsCorrect() {
        // Fork-unique, appId-derived (regenerated by syncForkConfig). DATABASE_NAME
        // delegates to the single source of truth, DatabaseConfig.NAME.
        assertEquals(DatabaseConfig.NAME, AppDatabase.DATABASE_NAME)
    }
}
