/*
 * Copyright 2025 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */
package kpt.core.database

import androidx.room3.AutoMigration
import androidx.room3.ColumnTypeConverters
import androidx.room3.ConstructedBy
import androidx.room3.Database
import androidx.room3.RoomDatabase
import androidx.room3.RoomDatabaseConstructor
import kpt.core.database.config.DatabaseConfig
import kpt.core.database.config.ForkDatabaseConfig

/**
 * KSP-generated constructor bridge for [AppDatabase].
 *
 * Room 3 requires an `expect object` annotated via [@ConstructedBy][ConstructedBy] so that
 * the KSP compiler plugin can generate a platform-specific `actual object` containing the
 * `AppDatabase_Impl` instantiation logic.
 */
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}

/**
 * Root Room 3 database for the application.
 *
 * This is a **commonMain** definition that works across all Kotlin Multiplatform targets
 * (Android, Desktop/JVM, iOS/Native, JS, WasmJS). Platform-specific database creation
 * is handled by [kpt.core.base.database.AppDatabaseFactory] in each platform's
 * DI module — see [kpt.core.database.di.DatabaseModule].
 *
 * Room 3 uses the [ConstructedBy] annotation to delegate instance creation to
 * [AppDatabaseConstructor], whose `actual` implementation is generated by KSP on
 * every target.
 *
 * ## White-label contract (E1/C7) — this file FULL-COPIES
 * `owner: template`: a template sync blind-copies this file, no 3-way merge. It was the LAST
 * hand-merged file under the `core` modules, because Room needs ONE compile-time `entities = [...]`
 * literal — a fork's tables cannot live in a separate file the way every other seam works.
 *
 * They do not need to be MERGED, though, only re-derived. Everything project-specific — demo AND
 * fork — is DECLARED in `app-profile/app.yaml#database` and projected into the five
 * `gen-*:begin`/`gen-*:end` regions below by `./gradlew syncForkConfig`, which the sync runs
 * immediately after the copy. So the copy lands with empty regions and the regen refills them from
 * the fork's own SoT.
 *
 * Hand-editing a `gen-*` region is pointless — the next syncForkConfig overwrites it. Declare it in
 * the owning module instead: the FRAMEWORK tables in `core-base/database/module-schema.yaml`, a
 * fork's own in `app-profile/app.yaml#database`. This file hardcodes NO entity or DAO at all — Room
 * forces the array literal to live here, but nothing decides its contents here.
 *
 * Generated members are referenced by FULLY-QUALIFIED name, never via an import: ktlint's
 * `standard:import-ordering` forbids both blank lines and comments inside the import block, so a
 * sentinel region cannot live there. Same reason `AppSupabaseAnonKeys` spells out
 * `kpt.core.network.BuildKonfig.<KEY>` inside its own generated block.
 *
 * ## Fresh-fork baseline
 * The demo declarations in app-profile sit inside a comment fence, so
 * `scripts/remove-demo.sh` strips them and the regions regenerate EMPTY. The schema history goes
 * with them (a fresh fork has no installed users to migrate) and the same script resets
 * [TEMPLATE_BASE_VERSION] to 1 — leaving a valid framework-only `@Database` at v1 with no
 * `autoMigrations`, which compiles and is coherent.
 *
 * ## Schema history (the template's own showcase DB; a fresh fork starts at v1)
 * | Version | Change |
 * |---------|--------|
 * | v3 → v4 | adds `framework_fetched_at` |
 * | v4 → v5 | adds `framework_submit_drafts` |
 * | v5 → v6 | adds `personal_watchlist` |
 * | v6 → v7 | adds `uniqueKey` column to drafts |
 * | v7 → v8 | adds `banking_loans` + `banking_bill_reminders` |
 * | v8 → v10 | adds `alerts` + `interest_rate_series`; drops `samples` |
 * | v10 → v12 | adds `cloud_todos`, `framework_write_conflicts` |
 * | v12 → v13 | adds `attemptCount` to `framework_submit_drafts` |
 */
@Database(
    entities = [
        kpt.core.base.database.infra.entity.BookkeeperEntity::class,
        kpt.core.base.database.infra.entity.FetchedAtEntity::class,
        kpt.core.base.database.infra.entity.DraftEntity::class,
        kpt.core.base.database.infra.entity.ConflictEntity::class,
        kpt.core.database.currency.entity.ExchangeRatesEntity::class,
        kpt.core.database.crypto.entity.CoinMarketEntity::class,
        kpt.core.database.crypto.entity.CoinDetailEntity::class,
        kpt.core.database.currency.entity.RateHistoryEntity::class,
        kpt.core.database.watchlist.entity.WatchlistEntity::class,
        kpt.core.database.banking.entity.LoanEntity::class,
        kpt.core.database.banking.entity.BillReminderEntity::class,
        kpt.core.database.alerts.AlertEntity::class,
        kpt.core.database.economic.InterestRateSeriesEntity::class,
        kpt.core.database.cloudtodo.CloudTodoEntity::class,
    ],
    version = AppDatabase.VERSION,
    exportSchema = true,
    autoMigrations = [
        AutoMigration(from = 4, to = 5),
        AutoMigration(from = 5, to = 6),
        AutoMigration(from = 6, to = 7),
        AutoMigration(from = 7, to = 8),
        AutoMigration(from = 8, to = 10, spec = kpt.core.database.migrations.MigrationSpec8to10::class),
        AutoMigration(from = 10, to = 11),
        AutoMigration(from = 11, to = 12),
        AutoMigration(from = 12, to = 13),
    ],
)
@ColumnTypeConverters(
    kpt.core.database.currency.converter.ChargeTypeConverters::class,
    kpt.core.database.crypto.converter.FintechTypeConverters::class,
    kpt.core.database.banking.converter.BankingTypeConverters::class,
)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {
    abstract val bookkeeperDao: kpt.core.base.database.infra.dao.BookkeeperDao
    abstract val fetchedAtDao: kpt.core.base.database.infra.dao.FetchedAtDao
    abstract val draftDao: kpt.core.base.database.infra.dao.DraftDao
    abstract val conflictDao: kpt.core.base.database.infra.dao.ConflictDao
    abstract val exchangeRatesDao: kpt.core.database.currency.dao.ExchangeRatesDao
    abstract val cloudTodoDao: kpt.core.database.cloudtodo.CloudTodoDao
    abstract val coinMarketDao: kpt.core.database.crypto.dao.CoinMarketDao
    abstract val coinDetailDao: kpt.core.database.crypto.dao.CoinDetailDao
    abstract val rateHistoryDao: kpt.core.database.currency.dao.RateHistoryDao
    abstract val watchlistDao: kpt.core.database.watchlist.dao.WatchlistDao
    abstract val loanDao: kpt.core.database.banking.dao.LoanDao
    abstract val billReminderDao: kpt.core.database.banking.dao.BillReminderDao
    abstract val alertDao: kpt.core.database.alerts.AlertDao
    abstract val interestRateSeriesDao: kpt.core.database.economic.InterestRateSeriesDao

    companion object {
        /**
         * Effective Room schema version — owned OUTRIGHT by the fork ([ForkDatabaseConfig], generated
         * from `app-profile/migration-ledger.yaml#version`). The template does not contribute to it;
         * it ships `migration_units` that the fork's ledger places at its own next free version.
         */
        const val VERSION = ForkDatabaseConfig.VERSION

        /** Fork-unique on-disk DB filename — single source of truth is [DatabaseConfig.NAME]
         *  (appId-derived, regenerated by `syncForkConfig`). All platform builders read this. */
        const val DATABASE_NAME = DatabaseConfig.NAME
    }
}
