/*
 * Copyright 2026 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */
package kpt.core.network.config

/**
 * The per-fork map of Supabase access-point id → anon key.
 *
 * **SoT: `app-profile/app.yaml#network.access_points`** (rows) **+ the build environment** (values).
 * The block below is GENERATED by `./gradlew syncForkConfig`: one row per point declaring
 * `type: supabase`, so a declared Supabase endpoint can no longer be missing a row.
 *
 * A point that also declares `anon_key_env: X` resolves to `BuildKonfig.X` — a build-time read of the
 * env var / `local.properties`, the same sanctioned path as `FRED_API_KEY`, so **no key is ever written
 * to a tracked file**. Without `anon_key_env` the row resolves to the empty string, which leaves the
 * client inert (`isConfigured == false`) rather than half-configured behind a fake key — the template
 * ships that way.
 *
 * Enforced by `scripts/product-health/checks/network-access-points.sh` (NAP-5/NAP-6).
 */
object AppSupabaseAnonKeys {
    // syncForkConfig:supabase-anon-keys:begin — GENERATED from app-profile/app.yaml.
    // One row per SUPABASE access point. `anon_key_env: X` on the point emits BuildKonfig.X
    // (build-time env / local.properties read, referenced by FQN so no import is needed
    // outside this block); no key is committed. Absent -> "" so the client stays inert.
    private val byId: Map<String, String> = mapOf(
        "project" to kpt.core.network.BuildKonfig.MY_SUPABASE_KEY,
    )
    // syncForkConfig:supabase-anon-keys:end

    /** Anon key for [id], or empty string if [id] is not registered. */
    fun forId(id: String): String = byId[id].orEmpty()
}
