/*
 * Copyright 2025 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */
package kpt.core.network.config

import kpt.core.base.network.UrlType

/**
 * Project-level catalogue of named API endpoints for runtime base-URL switching
 * (see [kpt.core.base.network.MultiUrlConfigProvider] / [kpt.core.base.network.DynamicBaseUrlPlugin]).
 *
 * [UrlType] is an **open** value class — `core-base` ships only the generic [UrlType.MAIN]; this is the
 * project's own vocabulary.
 *
 * **SoT: `app-profile/app.yaml#network.access_points`.** The block below is GENERATED by
 * `./gradlew syncForkConfig` — one constant per declared access point, named `id.uppercase()` to match
 * [kpt.core.base.network.AccessPoint.type]'s default. Add or rename endpoints in app-profile, not here.
 *
 * It is generated rather than hand-kept because the two must agree *exactly* and nothing forced them to:
 * this object had drifted to 3 constants against 8 declared points, and the failure was silent —
 * [AppMultiUrlConfigProvider.getBaseUrl] falls back to [UrlType.MAIN] for an unrecognised type, so
 * looking up a missing endpoint quietly returned the MAIN base URL instead of failing.
 */
object AppUrlTypes {
    // syncForkConfig:url-types:begin — GENERATED from app-profile/app.yaml#network.access_points.
    // One constant per declared access point (UrlType(id.uppercase()), matching
    // AccessPoint.type's default). Edit the access points THERE; do not hand-edit this block.

    /** `main` — REST access point. */
    val MAIN: UrlType = UrlType.MAIN

    /** `staging` — REST access point. */
    val STAGING: UrlType = UrlType("STAGING")

    /** `project` — Supabase access point. */
    val PROJECT: UrlType = UrlType("PROJECT")

    /** `jsonplaceholder` — REST access point. */
    val JSONPLACEHOLDER: UrlType = UrlType("JSONPLACEHOLDER")

    /** `frankfurter` — REST access point. */
    val FRANKFURTER: UrlType = UrlType("FRANKFURTER")

    /** `coingecko` — REST access point. */
    val COINGECKO: UrlType = UrlType("COINGECKO")

    /** `fred` — REST access point. */
    val FRED: UrlType = UrlType("FRED")

    /** `worldbank` — REST access point. */
    val WORLDBANK: UrlType = UrlType("WORLDBANK")

    /** Every declared endpoint type, in app-profile order. */
    val all: List<UrlType> = listOf(
        MAIN,
        STAGING,
        PROJECT,
        JSONPLACEHOLDER,
        FRANKFURTER,
        COINGECKO,
        FRED,
        WORLDBANK,
    )
    // syncForkConfig:url-types:end
}
